theme: jekyll-theme-slate

Title: Ryan Hoyles Homepage 

<p>I went to Sherando High School. I enjoy music, especially playing piano. I am also currently in an a capella group.</p>

<img src="https://assets.bonappetit.com/photos/58e29a4f8f4c125ce35a1301/16:9/w_1200,c_limit/0417-web-pupusa-beauty.jpg" alt="Pupusa">

<p><a href="http://www.se.rit.edu/~swen-101/00/index.html">SE Website</a></p>

<ul>
  <li>How to work properly in a team</li>
  <li>Using Javascript properly</li>
  <li>Getting better with github</li>
